### ISSUE TITLE
Enhancement: Make work plugin with Vimeo url, please!

### ISSUE THREAD

**Issue by llemurya** [FormstoneClassic/Wallpaper#13]
I will be very happy If this plugin will work with Vimeo urls, because i tested, it didn't work.Or maybe is another way to work with vimeo.If you know , tell me please.Thanks a lot!

**Comment by danyj** [comment]
:+1:

**Comment by benplum** [comment]
Unless the've changed their terms, Vimeo requires a pro account to access the full featured JS API.

**Comment by danyj** [comment]
I have few sliders that do not require pro account and use their API
here is one of them 
http://extensions.youjoomla.info/yj-media-slider.html
see second slide


https://developer.vimeo.com/player/js-api

and Froogaloop does not require anything special
https://f.vimeocdn.com/js/froogaloop2.min.js

did I misunderstand  "full featured" ?

**Comment by benplum** [comment]
You can't achieve a 'chromeless' player without a paid account, that's all. 

https://vimeo.com/forums/topic:14561
